{% set name = "pymatgen-io-fleur" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymatgen-io-fleur-{{ version }}.tar.gz
  sha256: 666ddca1c6d60d0be83c01eff25bc1e0c31872c5caf2c434b505d8088ee9f299

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core >=3.4,<4
  run:
    - masci-tools >=0.13
    - pymatgen >=2022.7.8
    - python >={{ python_min }}

test:
  imports:
    - pymatgen.io.fleur
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pymatgen-io-fleur/
  summary: A pymatgen add-on for IO for the fleur code.
  dev_url: https://github.com/JuDFTteam/pymatgen-io-fleur
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janssenhenning
