{% set name = "pymatgen-io-fleur" %}
{% set version = "0.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymatgen-io-fleur-{{ version }}.tar.gz
  sha256: 22528705e26217e9959b4326b966b3cbfc16b2d20065c8f97dca0b20d6be3bb2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - flit-core >=3.4,<4
  run:
    - masci-tools >=0.11.3,~=0.11
    - pymatgen >=2022.7.8
    - python >=3.8

test:
  imports:
    - pymatgen.io.fleur
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pymatgen-io-fleur/
  summary: A pymatgen add-on for IO for the fleur code.
  dev_url: https://github.com/JuDFTteam/pymatgen-io-fleur
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janssenhenning
